# Generated by Django 4.2.3 on 2023-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='doc',
            field=models.FileField(upload_to='static/fileUpload'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='profile',
            field=models.FileField(upload_to='static/fileUpload'),
        ),
    ]
